In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 30)
pd.set_option('display.precision', 3)

In [3]:
print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 0.25.0
Numpy version: 1.16.4

In [4]:
olive_path = 'http://s3.amazonaws.com/istreet-assets/cqj0wXOp6sICdTRWc5X2cw/olive.csv.txt'
df = pd.read_csv(olive_path)

In [5]:
df

,Unnamed: 0,region,area,palmitic,palmitoleic,stearic,oleic,linoleic,linolenic,arachidic,eicosenoic
0,1.North-Apulia,1,1,1075,75,226,7823,672,36,60,29
1,2.North-Apulia,1,1,1088,73,224,7709,781,31,61,29
2,3.North-Apulia,1,1,911,54,246,8113,549,31,63,29
3,4.North-Apulia,1,1,966,57,240,7952,619,50,78,35
4,5.North-Apulia,1,1,1051,67,259,7771,672,50,80,46
5,6.North-Apulia,1,1,911,49,268,7924,678,51,70,44
6,7.North-Apulia,1,1,922,66,264,7990,618,49,56,29
7,8.North-Apulia,1,1,1100,61,235,7728,734,39,64,35
8,9.North-Apulia,1,1,1082,60,239,7745,709,46,83,33
9,10.North-Apulia,1,1,1037,55,213,7944,633,26,52,30
10,11.North-Apulia,1,1,1051,35,219,7978,605,21,65,24
11,12.North-Apulia,1,1,1036,59,235,7868,661,30,62,44
12,13.North-Apulia,1,1,1074,70,214,7728,747,50,79,33
13,14.North-Apulia,1,1,875,52,243,8018,655,41,79,32
14,15.North-Apulia,1,1,952,49,254,7795,780,50,75,41
...,...,...,...,...,...,...,...,...,...,...,...
557,558.West-Liguria,3,8,1010,100,240,7710,910,10,20,2
558,559.West-Liguria,3,8,1020,90,240,7800,850,0,0,2
559,560.West-Liguria,3,8,1120,90,300,7650,830,0,10,1
560,561.West-Liguria,3,8,1090,90,290,7710,800,10,0,2
561,562.West-Liguria,3,8,1100,120,280,7630,770,10,10,2
562,563.West-Liguria,3,8,1090,80,240,7820,760,10,0,2
563,564.West-Liguria,3,8,1150,90,250,7720,810,0,10,3
564,565.West-Liguria,3,8,1110,90,230,7810,750,0,10,2
565,566.West-Liguria,3,8,1010,110,210,7720,950,0,0,1
566,567.West-Liguria,3,8,1070,100,220,7730,870,10,10,2
567,568.West-Liguria,3,8,1280,110,290,7490,790,10,10,2
568,569.West-Liguria,3,8,1060,100,270,7740,810,10,10,3
569,570.West-Liguria,3,8,1010,90,210,7720,970,0,0,2
570,571.West-Liguria,3,8,990,120,250,7750,870,10,10,2
571,572.West-Liguria,3,8,960,80,240,7950,740,10,20,2

In [6]:
shape = df.shape
shape

(572, 11)

df.info()

In [7]:
df_first_two = df.iloc[0:2]
df_first_two

,Unnamed: 0,region,area,palmitic,palmitoleic,stearic,oleic,linoleic,linolenic,arachidic,eicosenoic
0,1.North-Apulia,1,1,1075,75,226,7823,672,36,60,29
1,2.North-Apulia,1,1,1088,73,224,7709,781,31,61,29

In [8]:
data = len(df.dtypes.unique())
data

2

In [9]:
df['sub_region_raw'] = df['Unnamed: 0']
df

,Unnamed: 0,region,area,palmitic,palmitoleic,stearic,oleic,linoleic,linolenic,arachidic,eicosenoic,sub_region_raw
0,1.North-Apulia,1,1,1075,75,226,7823,672,36,60,29,1.North-Apulia
1,2.North-Apulia,1,1,1088,73,224,7709,781,31,61,29,2.North-Apulia
2,3.North-Apulia,1,1,911,54,246,8113,549,31,63,29,3.North-Apulia
3,4.North-Apulia,1,1,966,57,240,7952,619,50,78,35,4.North-Apulia
4,5.North-Apulia,1,1,1051,67,259,7771,672,50,80,46,5.North-Apulia
5,6.North-Apulia,1,1,911,49,268,7924,678,51,70,44,6.North-Apulia
6,7.North-Apulia,1,1,922,66,264,7990,618,49,56,29,7.North-Apulia
7,8.North-Apulia,1,1,1100,61,235,7728,734,39,64,35,8.North-Apulia
8,9.North-Apulia,1,1,1082,60,239,7745,709,46,83,33,9.North-Apulia
9,10.North-Apulia,1,1,1037,55,213,7944,633,26,52,30,10.North-Apulia
10,11.North-Apulia,1,1,1051,35,219,7978,605,21,65,24,11.North-Apulia
11,12.North-Apulia,1,1,1036,59,235,7868,661,30,62,44,12.North-Apulia
12,13.North-Apulia,1,1,1074,70,214,7728,747,50,79,33,13.North-Apulia
13,14.North-Apulia,1,1,875,52,243,8018,655,41,79,32,14.North-Apulia
14,15.North-Apulia,1,1,952,49,254,7795,780,50,75,41,15.North-Apulia
...,...,...,...,...,...,...,...,...,...,...,...,...
557,558.West-Liguria,3,8,1010,100,240,7710,910,10,20,2,558.West-Liguria
558,559.West-Liguria,3,8,1020,90,240,7800,850,0,0,2,559.West-Liguria
559,560.West-Liguria,3,8,1120,90,300,7650,830,0,10,1,560.West-Liguria
560,561.West-Liguria,3,8,1090,90,290,7710,800,10,0,2,561.West-Liguria
561,562.West-Liguria,3,8,1100,120,280,7630,770,10,10,2,562.West-Liguria
562,563.West-Liguria,3,8,1090,80,240,7820,760,10,0,2,563.West-Liguria
563,564.West-Liguria,3,8,1150,90,250,7720,810,0,10,3,564.West-Liguria
564,565.West-Liguria,3,8,1110,90,230,7810,750,0,10,2,565.West-Liguria
565,566.West-Liguria,3,8,1010,110,210,7720,950,0,0,1,566.West-Liguria
566,567.West-Liguria,3,8,1070,100,220,7730,870,10,10,2,567.West-Liguria
567,568.West-Liguria,3,8,1280,110,290,7490,790,10,10,2,568.West-Liguria
568,569.West-Liguria,3,8,1060,100,270,7740,810,10,10,3,569.West-Liguria
569,570.West-Liguria,3,8,1010,90,210,7720,970,0,0,2,570.West-Liguria
570,571.West-Liguria,3,8,990,120,250,7750,870,10,10,2,571.West-Liguria
571,572.West-Liguria,3,8,960,80,240,7950,740,10,20,2,572.West-Liguria

In [10]:
df.rename(columns={'Unnamed: 0':'sub_region_desc'},inplace=True)
df

,sub_region_desc,region,area,palmitic,palmitoleic,stearic,oleic,linoleic,linolenic,arachidic,eicosenoic,sub_region_raw
0,1.North-Apulia,1,1,1075,75,226,7823,672,36,60,29,1.North-Apulia
1,2.North-Apulia,1,1,1088,73,224,7709,781,31,61,29,2.North-Apulia
2,3.North-Apulia,1,1,911,54,246,8113,549,31,63,29,3.North-Apulia
3,4.North-Apulia,1,1,966,57,240,7952,619,50,78,35,4.North-Apulia
4,5.North-Apulia,1,1,1051,67,259,7771,672,50,80,46,5.North-Apulia
5,6.North-Apulia,1,1,911,49,268,7924,678,51,70,44,6.North-Apulia
6,7.North-Apulia,1,1,922,66,264,7990,618,49,56,29,7.North-Apulia
7,8.North-Apulia,1,1,1100,61,235,7728,734,39,64,35,8.North-Apulia
8,9.North-Apulia,1,1,1082,60,239,7745,709,46,83,33,9.North-Apulia
9,10.North-Apulia,1,1,1037,55,213,7944,633,26,52,30,10.North-Apulia
10,11.North-Apulia,1,1,1051,35,219,7978,605,21,65,24,11.North-Apulia
11,12.North-Apulia,1,1,1036,59,235,7868,661,30,62,44,12.North-Apulia
12,13.North-Apulia,1,1,1074,70,214,7728,747,50,79,33,13.North-Apulia
13,14.North-Apulia,1,1,875,52,243,8018,655,41,79,32,14.North-Apulia
14,15.North-Apulia,1,1,952,49,254,7795,780,50,75,41,15.North-Apulia
...,...,...,...,...,...,...,...,...,...,...,...,...
557,558.West-Liguria,3,8,1010,100,240,7710,910,10,20,2,558.West-Liguria
558,559.West-Liguria,3,8,1020,90,240,7800,850,0,0,2,559.West-Liguria
559,560.West-Liguria,3,8,1120,90,300,7650,830,0,10,1,560.West-Liguria
560,561.West-Liguria,3,8,1090,90,290,7710,800,10,0,2,561.West-Liguria
561,562.West-Liguria,3,8,1100,120,280,7630,770,10,10,2,562.West-Liguria
562,563.West-Liguria,3,8,1090,80,240,7820,760,10,0,2,563.West-Liguria
563,564.West-Liguria,3,8,1150,90,250,7720,810,0,10,3,564.West-Liguria
564,565.West-Liguria,3,8,1110,90,230,7810,750,0,10,2,565.West-Liguria
565,566.West-Liguria,3,8,1010,110,210,7720,950,0,0,1,566.West-Liguria
566,567.West-Liguria,3,8,1070,100,220,7730,870,10,10,2,567.West-Liguria
567,568.West-Liguria,3,8,1280,110,290,7490,790,10,10,2,568.West-Liguria
568,569.West-Liguria,3,8,1060,100,270,7740,810,10,10,3,569.West-Liguria
569,570.West-Liguria,3,8,1010,90,210,7720,970,0,0,2,570.West-Liguria
570,571.West-Liguria,3,8,990,120,250,7750,870,10,10,2,571.West-Liguria
571,572.West-Liguria,3,8,960,80,240,7950,740,10,20,2,572.West-Liguria

In [11]:
df.rename(columns={'area':'sub_region'},inplace=True)
df

,sub_region_desc,region,sub_region,palmitic,palmitoleic,stearic,oleic,linoleic,linolenic,arachidic,eicosenoic,sub_region_raw
0,1.North-Apulia,1,1,1075,75,226,7823,672,36,60,29,1.North-Apulia
1,2.North-Apulia,1,1,1088,73,224,7709,781,31,61,29,2.North-Apulia
2,3.North-Apulia,1,1,911,54,246,8113,549,31,63,29,3.North-Apulia
3,4.North-Apulia,1,1,966,57,240,7952,619,50,78,35,4.North-Apulia
4,5.North-Apulia,1,1,1051,67,259,7771,672,50,80,46,5.North-Apulia
5,6.North-Apulia,1,1,911,49,268,7924,678,51,70,44,6.North-Apulia
6,7.North-Apulia,1,1,922,66,264,7990,618,49,56,29,7.North-Apulia
7,8.North-Apulia,1,1,1100,61,235,7728,734,39,64,35,8.North-Apulia
8,9.North-Apulia,1,1,1082,60,239,7745,709,46,83,33,9.North-Apulia
9,10.North-Apulia,1,1,1037,55,213,7944,633,26,52,30,10.North-Apulia
10,11.North-Apulia,1,1,1051,35,219,7978,605,21,65,24,11.North-Apulia
11,12.North-Apulia,1,1,1036,59,235,7868,661,30,62,44,12.North-Apulia
12,13.North-Apulia,1,1,1074,70,214,7728,747,50,79,33,13.North-Apulia
13,14.North-Apulia,1,1,875,52,243,8018,655,41,79,32,14.North-Apulia
14,15.North-Apulia,1,1,952,49,254,7795,780,50,75,41,15.North-Apulia
...,...,...,...,...,...,...,...,...,...,...,...,...
557,558.West-Liguria,3,8,1010,100,240,7710,910,10,20,2,558.West-Liguria
558,559.West-Liguria,3,8,1020,90,240,7800,850,0,0,2,559.West-Liguria
559,560.West-Liguria,3,8,1120,90,300,7650,830,0,10,1,560.West-Liguria
560,561.West-Liguria,3,8,1090,90,290,7710,800,10,0,2,561.West-Liguria
561,562.West-Liguria,3,8,1100,120,280,7630,770,10,10,2,562.West-Liguria
562,563.West-Liguria,3,8,1090,80,240,7820,760,10,0,2,563.West-Liguria
563,564.West-Liguria,3,8,1150,90,250,7720,810,0,10,3,564.West-Liguria
564,565.West-Liguria,3,8,1110,90,230,7810,750,0,10,2,565.West-Liguria
565,566.West-Liguria,3,8,1010,110,210,7720,950,0,0,1,566.West-Liguria
566,567.West-Liguria,3,8,1070,100,220,7730,870,10,10,2,567.West-Liguria
567,568.West-Liguria,3,8,1280,110,290,7490,790,10,10,2,568.West-Liguria
568,569.West-Liguria,3,8,1060,100,270,7740,810,10,10,3,569.West-Liguria
569,570.West-Liguria,3,8,1010,90,210,7720,970,0,0,2,570.West-Liguria
570,571.West-Liguria,3,8,990,120,250,7750,870,10,10,2,571.West-Liguria
571,572.West-Liguria,3,8,960,80,240,7950,740,10,20,2,572.West-Liguria

In [12]:
df['region'].unique()

array([1, 2, 3])

In [13]:
len(df['sub_region'].unique())

9

In [14]:
df['sub_region'].unique()

array([1, 2, 3, 4, 5, 6, 9, 7, 8])

In [15]:
df['sub_region_desc'] = df['sub_region_desc'].apply(lambda x: x.split('.')[1])
df

,sub_region_desc,region,sub_region,palmitic,palmitoleic,stearic,oleic,linoleic,linolenic,arachidic,eicosenoic,sub_region_raw
0,North-Apulia,1,1,1075,75,226,7823,672,36,60,29,1.North-Apulia
1,North-Apulia,1,1,1088,73,224,7709,781,31,61,29,2.North-Apulia
2,North-Apulia,1,1,911,54,246,8113,549,31,63,29,3.North-Apulia
3,North-Apulia,1,1,966,57,240,7952,619,50,78,35,4.North-Apulia
4,North-Apulia,1,1,1051,67,259,7771,672,50,80,46,5.North-Apulia
5,North-Apulia,1,1,911,49,268,7924,678,51,70,44,6.North-Apulia
6,North-Apulia,1,1,922,66,264,7990,618,49,56,29,7.North-Apulia
7,North-Apulia,1,1,1100,61,235,7728,734,39,64,35,8.North-Apulia
8,North-Apulia,1,1,1082,60,239,7745,709,46,83,33,9.North-Apulia
9,North-Apulia,1,1,1037,55,213,7944,633,26,52,30,10.North-Apulia
10,North-Apulia,1,1,1051,35,219,7978,605,21,65,24,11.North-Apulia
11,North-Apulia,1,1,1036,59,235,7868,661,30,62,44,12.North-Apulia
12,North-Apulia,1,1,1074,70,214,7728,747,50,79,33,13.North-Apulia
13,North-Apulia,1,1,875,52,243,8018,655,41,79,32,14.North-Apulia
14,North-Apulia,1,1,952,49,254,7795,780,50,75,41,15.North-Apulia
...,...,...,...,...,...,...,...,...,...,...,...,...
557,West-Liguria,3,8,1010,100,240,7710,910,10,20,2,558.West-Liguria
558,West-Liguria,3,8,1020,90,240,7800,850,0,0,2,559.West-Liguria
559,West-Liguria,3,8,1120,90,300,7650,830,0,10,1,560.West-Liguria
560,West-Liguria,3,8,1090,90,290,7710,800,10,0,2,561.West-Liguria
561,West-Liguria,3,8,1100,120,280,7630,770,10,10,2,562.West-Liguria
562,West-Liguria,3,8,1090,80,240,7820,760,10,0,2,563.West-Liguria
563,West-Liguria,3,8,1150,90,250,7720,810,0,10,3,564.West-Liguria
564,West-Liguria,3,8,1110,90,230,7810,750,0,10,2,565.West-Liguria
565,West-Liguria,3,8,1010,110,210,7720,950,0,0,1,566.West-Liguria
566,West-Liguria,3,8,1070,100,220,7730,870,10,10,2,567.West-Liguria
567,West-Liguria,3,8,1280,110,290,7490,790,10,10,2,568.West-Liguria
568,West-Liguria,3,8,1060,100,270,7740,810,10,10,3,569.West-Liguria
569,West-Liguria,3,8,1010,90,210,7720,970,0,0,2,570.West-Liguria
570,West-Liguria,3,8,990,120,250,7750,870,10,10,2,571.West-Liguria
571,West-Liguria,3,8,960,80,240,7950,740,10,20,2,572.West-Liguria

In [18]:
srd_un = df['sub_region_desc'].unique()

In [19]:
srd_un

array(['North-Apulia', 'Calabria', 'South-Apulia', 'Sicily',
       'Inland-Sardinia', 'Coast-Sardinia', 'Umbria', 'East-Liguria',
       'West-Liguria'], dtype=object)